#! /usr/bin/python

import argparse
import ast
import os


# Parse command line arguments
aparser = argparse.ArgumentParser(description='ThunderViper: Thunderizes Python code into Assembly using real lightening!')
aparser.add_argument('file', metavar='file.py', type=str, 
					help='The Python file with which to Thunderize.')\

args = aparser.parse_args()


# Tell the world what job ThunderViper is doing
print 'Thunderizing file:', args.file
print 'In mode: AMD64'


# Open file for reading
completeFileName = os.path.abspath(args.file)
inFile = open(completeFileName, 'r')


# After everything is all said and done, say that ThunderViper is finished
print "Done!"
