#! /usr/bin/python

import argparse
import os
import program_mapper


# Parse command line arguments
aparser = argparse.ArgumentParser(description='ThunderViper: Thunderizes Python code into Assembly using real lightening!')
aparser.add_argument('file', metavar='file.py', type=str, 
					help='The Python file with which to Thunderize.')\

args = aparser.parse_args()


# Tell the world what job ThunderViper is doing
print 'Thunderizing file:', args.file
print 'In mode: AMD64'


# Open file for reading
completeFileName = os.path.abspath(args.file)
inFile = open(completeFileName, 'r')


# Get the lines as a list of them
lines = inFile.readlines()


# For each line, remove the trailing whitespace
for i in range(len(lines)):
	lines[i] = lines[i].rstrip()
	

# Now parse each line into the program mapper
progMap = program_mapper.ProgramMap()

for line in lines:
	progMap.parse(line)

# After everything is parsed in, dump out a program map in HTML
htmlFilename = os.path.abspath("DUMP_ProgMap.html")
progMap.dump(htmlFilename)


# After everything is all said and done, say that ThunderViper is finished
print "Done!"